### ISSUE TITLE
php 5.4 requirement

### ISSUE THREAD

**Issue by bvarent** [phpro/zf-doctrine-hydration-module#13]
Perhaps a requirement for php 5.4 could be added to composer.json.
(Since short array notation is used at least once, [here](/phpro/zf-doctrine-hydration-module/blob/master/src/Service/DoctrineHydratorFactory.php#L297)).

**Comment by veewee** [comment]
The minimum PHP version is added to the composer file on master:
https://github.com/phpro/zf-doctrine-hydration-module/commit/5afd5a2d78627e1c9f45a0203602df943eac2eea

Thanks!
