### ISSUE TITLE
entity_class setting should not be required

### ISSUE THREAD

**Issue by Bilge** [phpro/zf-doctrine-hydration-module#23]
A hydrator should be able to hydrate any document passed. The `entity_class` setting implies having to specify a different hydrator for every entity in the system that one may wish to hydrate, which is impractical and cumbersome to implement for large systems.

**Comment by veewee** [comment]
The idea is to create a configurable custom hydrator per entity. 
If you want a global hydrator, you should be using the default `DoctrineObject` hydrator.
