### ISSUE TITLE
Multiple properties with same strategy have field name set to last added strategy

### ISSUE THREAD

**Issue by rkeet** [phpro/zf-doctrine-hydration-module#42]
Possibly a bug, need help.

It's as if all strategies get added by reference, as such, setting the property name on the strategy, sets it for all where this same instance has been added. They all have the same object hash. 

Considering the following strategy configuration for a Resource:

```php
    'doctrine-hydrator' => [
        'Company\\V1\\Rest\\Company\\CompanyHydrator' => [
            'entity_class' => \Namespace\Path\To\Company\Entity\Company::class,
            'object_manager' => 'doctrine.entitymanager.orm_default',
            'by_value' => true,
            'strategies' => [
                'users' => \ZF\Doctrine\Hydrator\Strategy\CollectionLink::class,
                'countries' => \Application\Strategy\CollectionUniDirectionalToManyStrategy::class,
                'currencies' => \Application\Strategy\CollectionUniDirectionalToManyStrategy::class,
            ],
        ],
    ],
```

To have your information complete, this is the entire custom strategy:

```php
class CollectionUniDirectionalToManyStrategy extends AllowRemoveByValue
{
    public function extract($value)
    {
        return new Collection($value ?: []);
    }
}
```

So, when stepping through into the strategy during hydration for Countries, I expect to see that the `collectionName` of `$this` (instance of `CollectionUniDirectionalToManyStrategy`), is set to `countries`, however, it is set to `currencies`. See the debug image below for reference.

![image](https://user-images.githubusercontent.com/3327864/49580886-5dba7200-f950-11e8-80ab-4d80d7e2aa43.png)

This is due to how these are set in the `DoctrineHydratorFactory`, [here](https://github.com/phpro/zf-doctrine-hydration-module/blob/3b9b7cd527f46dd727b2a4dbd5c73c84ee0540fa/src/Service/DoctrineHydratorFactory.php#L329). 

    $strategy = $container->get($strategyKey);

Following that into the Zend `ServiceManager` we find this ([here](https://github.com/zendframework/zend-servicemanager/blob/0aea76faf40350852fd6570cb4c1eb60a18ac872/src/ServiceManager.php#L182)):

        // We start by checking if we have cached the requested service (this
        // is the fastest method).
        if (isset($this->services[$requestedName])) {
            return $this->services[$requestedName];
        }

This causes that the same instance is always returned. So when later the collection name is applied to 1 of the these "set" instances, it's applied to all of them. Creating the situation in the screenshot.

---

The bug fix:

Clone the result from the Zend `ServiceManager` to prevent using cached instances. 

    $strategy = clone $container->get($strategyKey);

**Comment by veewee** [comment]
Another solution would be to mark the strategy as not shared in the service configuration.
See `shared` section in the documentation: https://docs.zendframework.com/zend-servicemanager/configuring-the-service-manager/
